name: 'Check Compatibility'

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      # See: https://github.com/KohlbacherLab/dnpm-dip-api-gateway/blob/main/app/controllers/README.md#synthetic-json-data
      - name: Download synthetic mtb patient record
        run: curl -f -L https://preview.dnpm-dip.net/api/mtb/fake/data/patient-record -o ./tests/mv64e-mtb-fake-patient.json

      - name: Run tests
        run: go test
